#include <stdio.h>
//Shift distance definition and mask for bit fields
#define OPCODE_SHIFT 26
#define RS_SHIFT 21
#define RT_SHIFT 16
#define RD_SHIFT 11
#define SHAMT_SHIFT 6
#define ADDR_MASK 0X3FFFFFF
#define IMM_MASK 0XFFFF

//Opcode and functions definition
#define SPECIAL_OP 0
#define ADD_FUN 0X20
#define ADDI_OP 0X8
#define ADDIU_OP 0X9
#define ADDU_FUN 0X21
#define AND_FUN 0X24
#define ANDI_OP 0Xc
#define BEQ_OP 0X4
#define REGIMM_OP 0X1
#define BGEZ_BR 0X1
#define BGEZAL_BR 0X11
#define BGTZ_OP 0X7
#define BLEZ_OP 0X6
#define BLTZAL_BR 0X10
#define BNE_OP 0X5
#define J_OP 0X2
#define JAL_OP 0X3
#define LUI_OP 0XF
#define LW_OP 0X23
#define MFHI_FUN 0X10
#define MFLO_FUN 0X12
#define MULT_FUN 0X18
#define MULTU_FUN 0X19
#define NOR_FUN 0X27
#define OR_FUN 0X25
#define ORI_OP 0XD
#define SLL_FUN 0X30
#define SLLV_FUN 0X4
#define SRA_FUN 0X3
#define SRAV_FUN 0X7
#define SRL_FUN 0X2
#define SRLV_FUN 0X6
#define SUB_FUN 0X22
#define SUBU_FUN 0X23
#define SW_OP 0X2B
#define XOR_FUN 0X26
#define XORI_OP 0XE

#define ROM_HEAD "memory_initialization_radix=2;\nmemory_initialization_vector=\n"

#define __SLTI(source,destiny,immediate) immediate_instr(10,source,destiny,immediate,mips_app)
#define __PROBE(source)	immediate_instr(16,source,0,0,mips_app)
#define __ADD(source1,source2,destiny) special_instr(0,source1,source2,destiny,0,ADD_FUN,mips_app)
#define __ADDI(source,destiny,immediate) immediate_instr(ADDI_OP,source,destiny,immediate,mips_app)
#define __ADDIU(source,destiny,immediate) immediate_instr(ADDIU_OP,source,destiny,immediate,mips_app)
#define __ADDU(source1,source2,destiny) special_instr(0,source1,source2,destiny,0,ADDIU_FUN,mips_app)
#define __AND(source1,source2,destiny) specital_instr(0,source1,source2,destiny,0,AND_FUN,mips_app)
#define __ANDI(source,destiny,immediate) immediate_instr(ANDI_OP,source,destiny,immediate,mips_app)
#define __BEQ(source1,source2,offset) immediate_instr(BEQ_OP,source1,source2,offset,mips_app)
#define __BGEZ(source,offset) immediate_instr(REGIMM_OP,source,BGEZ_BR,offset,mips_app)
#define __BGEZAL(source,offset) immediate_instr(REGIMM_OP,source,BGEZAL_BR,offset,mips_app)
#define __BGTZ(source,offset) immediate_instr(BGTZ_OP,source,0,offset,mips_app)
#define __BLEZ(source,offset) immediate_instr(BLEZ_OP,source,0,offset,mips_app)
#define __BLTZ(source,offset) immediate_instr(BLTZ_OP,source,0,offset,mips_app)
#define __BLTZAL(source,offset) immediate_instr(REGIMM_OP,source,BLTZAL_BR,offset,mips_app)
#define __BNE(source1,source2,offset) immediate_instr(BNE_OP,source1,source2,offset,mips_app)
#define __J(address) jump_instr(J_OP,address,mips_app)
#define __JAL(address) jump_instr(JAL_OP,address,mips_app)
#define __LUI(destiny,immediate) immediate_instr(LUI_OP,0,destiny,immediate,mips_app)
#define __LW(base,destiny,offset) immediate_instr(LW_OP,base,destiny,offset,mips_app)
#define __MFHI(destiny) special_instr(0,0,0,destiny,0,MFHI_FUN,mips_app)
#define __MFLO(destiny) special_instr(0,0,0,destiny,0,MFLO_FUN,mips_app)
#define __MULT(source1,source2) special_instr(0,source1,source2,0,0,MULT_FUN,mips_app)
#define __MULTU(source1,source2) special_instr(0,source1,source2,0,0,MULTU_FUN,mips_app)
#define __NOR(source1,source2,destiny) special_instr(0,source1,source2,destiny,0,NOR_FUN,mips_app)
#define __OR(source1,source2,destiny) special_instr(0,source1,source2,destiny,0,OR_FUN,mips_app)
#define __ORI(source,destiny,immediate) immediate_instr(ORI_OP,source,destiny,immediate,mips_app)
#define __SLL(source,destiny,shamt) special_instr(0,0,source,destiny,shamt,SLL_FUN,mips_app)
#define __SLLV(source,destiny,vshamt) special_instr(0,vshamt,source,destiny,0,SLLV_FUN,mips_app)
#define __SRA(source,destiny,shamt) special_instr(0,0,source,destiny,shamt,SRA_FUN,mips_app)
#define __SRAV(source,desitny,vshamt) special_instr(0,vshamt,source,destiny,0,SRAV_FUN,mips_app)
#define __SRL(source,destiny,shamt) special_instr(0,0,source,destiny,shamt,SRL_FUN,mips_app)
#define __SRLV(source,destiny,vshamt) special_instr(0,vshamt,source,destiny,0,SRLV_FUN,mips_app)
#define __SUB(source1,source2,destiny) special_instr(0,source1,source2,destiny,0,SUB_FUN,mips_app)
#define __SUBU(source1,source2,destiny) special_instr(0,source1,source2,destiny,0,SUBU_FUN,mips_app)
#define __SW(base,source,offset) immediate_instr(SW_OP,base,source,offset,mips_app)
#define __XOR(source1,source2,destiny) special_instr(0,source1,source2,destiny,0,XOR_FUN,mips_app)
#define __XORI(source,destiny,immediate) immediate_instr(XORI_OP,source,detiny,immediate,mips_app)
